version: '3.7'

services:
  postgres:
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=sv_SE.UTF8"
      POSTGRES_HOST_AUTH_METHOD: trust
    image: postgres:11-alpine
    ports:
      - 5432:5432
