CREATE TABLE "bar" (
    "id" BIGINT PRIMARY KEY,
    "name" TEXT NOT NULL
);

CREATE TABLE "foo" (
    "id" BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "bar_id" BIGINT NOT NULL REFERENCES "bar"("id") ON DELETE CASCADE
);
